// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljwbdafyqjxlidgvmpzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqd2JkYWZ5cWp4bGlkZ3ZtcHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjA3OTgsImV4cCI6MjA2OTk5Njc5OH0.6gz4MBTGuUe6L3iTqERI_wJye4_AiTMX5ethymnFbH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});